# -*- coding: utf-8 -*-
""""Hello Neural Network!".ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wfjQBFWmhgxTlCc7h8DBiaCKrxNGxxfn

**Importing our libraries and API**
"""

import tensorflow as tf
from tensorflow import keras
import numpy as np

"""**Defining and compiling our NN**"""

model= keras.Sequential([keras.layers.Dense(units=1,input_shape=[1])])
model.compile(optimizer='sgd', loss='mean_squared_error')

"""**Our data**"""

Xs= np.array([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0], dtype=float)
Ys= np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype=float)

"""**Taining our neural network**"""

model.fit(Xs,Ys, epochs=100)

print(model.predict([10]))